version: '3.0'
services:
  chat-client:
    build: ./chat-app
    ports:
      - 5000:5173
    environment:
      VITE_SERVER_URL: http://localhost:3000

  chat-server:
    build: ./chat-app-server
    ports:
      - 3000:3000
    environment:
      PORT: 3000